### ISSUE TITLE
[BUG] Cannot install ms-recommenders==0.6.0 from PyPI

### ISSUE THREAD

**Issue by limdauto** [microsoft/recommenders#1482]
### Description

I cannot install `ms-recommenders==0.6.0` from PyPI.

### In which platform does it happen?

* OS: MacOS Catalina (Version 10.15.7)
* Python 3.7.10

### How do we replicate the issue?

* Create a fresh conda environment `conda create -n europython-2021 python=3.7`
* Run `pip install ms-recommenders==0.6.0` (I also tried `pip install --no-cache-dir ms-recommenders==0.6.0`

### Expected behavior (i.e. solution)

`ms-recommenders` should be installed.

### Other Comments

Stacktrace

```bash
❯ pip install ms-recommenders==0.6.0
Collecting ms-recommenders==0.6.0
  Using cached ms_recommenders-0.6.0.tar.gz (181 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/lim_Hoang/opt/anaconda3/envs/europython-2021/bin/python /Users/lim_Hoang/opt/anaconda3/envs/europython-2021/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/c4/tjglp9vs697fxvsfrnrs966w0000gn/T/tmpjtyzdi6k
       cwd: /private/var/folders/c4/tjglp9vs697fxvsfrnrs966w0000gn/T/pip-install-2fg0b2ks/ms-recommenders_32b163c415eb49a088dc446f8e7db69d
  Complete output (16 lines):
  Traceback (most recent call last):
    File "/Users/lim_Hoang/opt/anaconda3/envs/europython-2021/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/Users/lim_Hoang/opt/anaconda3/envs/europython-2021/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/lim_Hoang/opt/anaconda3/envs/europython-2021/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/c4/tjglp9vs697fxvsfrnrs966w0000gn/T/pip-build-env-c74psp9c/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 155, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/private/var/folders/c4/tjglp9vs697fxvsfrnrs966w0000gn/T/pip-build-env-c74psp9c/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/c4/tjglp9vs697fxvsfrnrs966w0000gn/T/pip-build-env-c74psp9c/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 17, in <module>
      with open(here.joinpath("reco_utils", "README.md"), encoding="utf-8") as f:
  FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/c4/tjglp9vs697fxvsfrnrs966w0000gn/T/pip-install-2fg0b2ks/ms-recommenders_32b163c415eb49a088dc446f8e7db69d/reco_utils/README.md'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/7a/ff/4a76f1282da568e64c43277236bfe0e464307fee614ecd46b7ba7ea3698a/ms_recommenders-0.6.0.tar.gz#sha256=b5a624ebb7791146e766bfc5a6009f8e2c2a30144eae4b8992566d1e57633bc7 (from https://pypi.org/simple/ms-recommenders/) (requires-python:>=3.6, <=3.7.10). Command errored out with exit status 1: /Users/lim_Hoang/opt/anaconda3/envs/europython-2021/bin/python /Users/lim_Hoang/opt/anaconda3/envs/europython-2021/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/c4/tjglp9vs697fxvsfrnrs966w0000gn/T/tmpjtyzdi6k Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement ms-recommenders==0.6.0 (from versions: 0.6.0)
ERROR: No matching distribution found for ms-recommenders==0.6.0
```

**Comment by limdauto** [comment]
I did some digging. The tar ball on PyPI [here](https://files.pythonhosted.org/packages/7a/ff/4a76f1282da568e64c43277236bfe0e464307fee614ecd46b7ba7ea3698a/ms_recommenders-0.6.0.tar.gz) has `README.md` outside of `reco_utils`, which is why it doesn't work because `setup.py` assumes it's inside.

Installing from Github works because the README is inside `reco_utils`, but I have to run:

```
pip install -e git+https://github.com/microsoft/recommenders/#egg=ms-recommenders
```

instead of the suggested command by the documentation:

```
pip install -e git+https://github.com/microsoft/recommenders/#egg=pkg
```

**Comment by dciborow** [comment]
I see the issue here.
As a workaround, are you able to use this command?
`pip install --only-binary :all: ms-recommenders==0.6.0`

I see the issue in the source distribution, but until we get a fixed version up this command may work instead.

**Comment by k9luo** [comment]
@dciborow Hi! Thanks for your suggestion. I tried this command `pip install --only-binary :all: ms-recommenders==0.6.0`. However, I got the following error message:
```
ERROR: Could not find a version that satisfies the requirement lightfm<2,>=1.15 (from ms-recommenders) (from versions: none)
ERROR: No matching distribution found for lightfm<2,>=1.15
```

**Comment by gramhagen** [comment]
please use [recommenders](https://pypi.org/project/recommenders/) package on pypi, we are deprecating ms-recommenders

the following commands worked for me, let me know if you still have issues:
```
conda create -n recopy37 python=3.7 -y
conda activate recopy37
pip install recommenders==0.6.0
```

**Comment by oliver-causey** [comment]
I am trying to run this library on azure DataBricks. This library requires Python 3.6 or Python 3.7. However, the Python 3 on DataBricks is Python 3.8.8, with no option to downgrade. I have been unable to find a workaround for this. Does anyone have any suggestions?
