### ISSUE TITLE
[BUG] recommenders==0.7.0 failed to install on Azure Databricks Runtime version 7.3 LTS

### ISSUE THREAD

**Issue by simonzhaoms** [microsoft/recommenders#1600]
### Description

recommenders 0.7.0 failed to be installed on Azure Databricks runtime version 7.3 LTS with the error:

```
java.lang.RuntimeException: ManagedLibraryInstallFailed: org.apache.spark.SparkException: Process List(/databricks/python/bin/pip, install, recommenders==0.7.0, --disable-pip-version-check) exited with code 2. ERROR: Exception:
Traceback (most recent call last):
  File "/databricks/python3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/databricks/python3/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/databricks/python3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/databricks/python3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/databricks/python3/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/databricks/python3/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/databricks/python3/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/databricks/python3/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/databricks/python3/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 96, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/databricks/python3/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 152, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/databricks/python3/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 255, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/databricks/python3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 63, in _build_backend
    obj = import_module(mod_path)
  File "/databricks/python3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 5, in <module>
    import distutils.core
  File "/tmp/pip-build-env-vdzjm90b/overlay/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 92, in create_module
    return importlib.import_module('setuptools._distutils')
  File "/databricks/python3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'setuptools._distutils'

 for library:PythonPyPiPkgId(recommenders,Some(0.7.0),None,List()),isSharedLibrary=false
Done
```

### In which platform does it happen?

[Azure Databricks Runtime version 7.3 LTS](https://docs.microsoft.com/en-us/azure/databricks/release-notes/runtime/7.3)

### How do we replicate the issue?

Install it in a cluster with Databricks runtime version 7.3 LTS (includes Apache Spark 3.0.1, Scala 2.12).

<img width="643" alt="Screenshot 2021-12-22 at 16 11 56" src="https://user-images.githubusercontent.com/43029286/147058731-b420b772-a004-4d87-99b1-f47fd29c3cf5.png">

<img width="712" alt="Screenshot 2021-12-22 at 16 11 31" src="https://user-images.githubusercontent.com/43029286/147058814-b8e3e79e-cda0-4203-b654-57b6a181de1e.png">

**Comment by simonzhaoms** [comment]
And it failed to install on [ADB 9.1+](https://docs.microsoft.com/en-us/azure/databricks/release-notes/runtime/9.1) either with the following error:

```
java.lang.RuntimeException: ManagedLibraryInstallFailed: org.apache.spark.SparkException: Process List(/databricks/python/bin/pip, install, recommenders==0.7.0, --disable-pip-version-check) exited with code 1.
ERROR: Could not find a version that satisfies the requirement recommenders==0.7.0
ERROR: No matching distribution found for recommenders==0.7.0
 for library:PythonPyPiPkgId(recommenders,Some(0.7.0),None,List()),isSharedLibrary=false
```

**Comment by miguelgfierro** [comment]
@simonzhaoms this is fixed, right?

**Comment by simonzhaoms** [comment]
The new version 1.0.0 now works
