### ISSUE TITLE
[ASK] SARPlus installation failed

### ISSUE THREAD

**Issue by zsonglorman** [microsoft/recommenders#1607]
Hello, I would like to use the SARPlus algorithm, but I can't install it using pip:

`pip install pysarplus`

Collecting pysarplus
  Using cached pysarplus-0.5.2.tar.gz (9.5 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\program files (x86)\microsoft visual studio\shared\python37_64\python.exe' 'c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\PETERK~1\AppData\Local\Temp\tmp1z4nnwfk'
       cwd: C:\Users\PETERK~1\AppData\Local\Temp\pip-install-gtlek_6c\pysarplus_33f387ccf830432d85323ab9f4790976
  Complete output (16 lines):
  Traceback (most recent call last):
    File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\PETERK~1\AppData\Local\Temp\pip-build-env-ybfe1gmv\overlay\Lib\site-packages\setuptools\build_meta.py", line 163, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "C:\Users\PETERK~1\AppData\Local\Temp\pip-build-env-ybfe1gmv\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "C:\Users\PETERK~1\AppData\Local\Temp\pip-build-env-ybfe1gmv\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 62, in <module>
      extra_compile_args=sysconfig.get_config_var("CFLAGS").split() + ["-std=c++11", "-Wall", "-Wextra"],
  AttributeError: 'NoneType' object has no attribute 'split'

What could be the problem? I'm on Windows 10, with Spark 3.2.0 and Hadoop 3.2 already installed.
Thank you in advance.

**Comment by miguelgfierro** [comment]
FYI @simonzhaoms

**Comment by simonzhaoms** [comment]
Hi @zsonglorman, Windows is not supported currently.  We'll try to see if we can make it available on Windows.

**Comment by zsonglorman** [comment]
Okay, thanks for your answer!
