### ISSUE TITLE
[ASK] MIND competition submission error using nrms_MIND.ipynb

### ISSUE THREAD

**Issue by leemengtaiwan** [microsoft/recommenders#1673]
### Description

Hi, thanks for creating the repo and MIND competition.

I tried to generate a valid MIND test submission using the latest version of [examples/00_quick_start/nrms_MIND.ipynb](https://github.com/microsoft/recommenders/blob/main/examples/00_quick_start/nrms_MIND.ipynb) by changing only this line to use the original MIND dataset:

```python
MIND_type = 'large'
```

After the `prediction.zip` was uploaded to [MIND competition](https://competitions.codalab.org/competitions/24122#participate) with user name: `leemeng`, I encountered an error message which is hard to debug by myself:

```bash
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/tmp/codalab/tmpbVMoKT/run/program/evaluate.py:17: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 28 but corresponding boolean dimension is 16
  false_score = score[label==0]
/tmp/codalab/tmpbVMoKT/run/program/evaluate.py:18: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 28 but corresponding boolean dimension is 16
  positive_score = score[label==1]
Traceback (most recent call last):
  File "/tmp/codalab/tmpbVMoKT/run/program/evaluate.py", line 125, in 
    auc, mrr, ndcg, ndcg10,mrrs = scoring(truth_file, submission_answer_file)
  File "/tmp/codalab/tmpbVMoKT/run/program/evaluate.py", line 91, in scoring
    mrr = mrr_score(y_true,y_score)
  File "/tmp/codalab/tmpbVMoKT/run/program/evaluate.py", line 36, in mrr_score
    y_true = np.take(y_true, order)
  File "/opt/conda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 124, in take
    return take(indices, axis, out, mode)
IndexError: index 21 is out of bounds for size 16
```

Previous, there was a similar issue (#1192), but that issue was considered to be caused by a small number of lines (7,538).
I have confirmed my second submitted `prediction.txt` in `prediction.zip` has many lines (376,471 lines):

```python
import pandas as pd
predictions = pd.read_csv(
    os.path.join(data_path, 'prediction.txt'), sep=" ", header=None,
    names=['id', 'rank']
)
len(predictions)
# output: 376471
```

Any help would be really appreciated. 🙏

**Comment by leemengtaiwan** [comment]
I also tried to use the news/behaviors files in **Test Set** directly to generate the `prediction.txt` but still failed to pass the `mrr_score` computation during online evaluation:

<img width="933" alt="image" src="https://user-images.githubusercontent.com/3454980/158310456-e6871df8-5ecc-4aeb-9b5c-3e2c12534141.png">


```bash
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/tmp/codalab/tmpDVNd1I/run/program/evaluate.py:17: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 116 but corresponding boolean dimension is 7
  false_score = score[label==0]
/tmp/codalab/tmpDVNd1I/run/program/evaluate.py:18: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 116 but corresponding boolean dimension is 7
  positive_score = score[label==1]
Traceback (most recent call last):
  File "/tmp/codalab/tmpDVNd1I/run/program/evaluate.py", line 125, in 
    auc, mrr, ndcg, ndcg10,mrrs = scoring(truth_file, submission_answer_file)
  File "/tmp/codalab/tmpDVNd1I/run/program/evaluate.py", line 91, in scoring
    mrr = mrr_score(y_true,y_score)
  File "/tmp/codalab/tmpDVNd1I/run/program/evaluate.py", line 36, in mrr_score
    y_true = np.take(y_true, order)
  File "/opt/conda/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 124, in take
    return take(indices, axis, out, mode)
IndexError: index 85 is out of bounds for size 7
```

**Comment by TacoOliver** [comment]
I have the same problem. Any help would be really appreciated.

**Comment by yjw1029** [comment]
The code in the notebook generates predictions for validation file. 376,471 is the number of lines of validation dataset.
![image](https://user-images.githubusercontent.com/32158211/158575484-5d2fb3c8-821c-4252-9ef4-59ed40ecf97f.png)

Please download the test dataset of MIND from https://mind201910small.blob.core.windows.net/release/MINDlarge_test.zip', and change the input parameter of `run_fast_eval`.

**Comment by leemengtaiwan** [comment]
@yjw1029 

Thank you so much for the response! 
This time I downloaded the test set and updated the input parameter of the function to run the evaluation on the test set:

```python
!wget https://mind201910small.blob.core.windows.net/release/MINDlarge_test.zip
!unzip MINDlarge_test.zip -d MINDlarge_test/

test_news_file = "MINDlarge_test/news.tsv"
test_behaviors_file = "MINDlarge_test/behaviors.tsv"

iterator = MINDIterator
model = NRMSModel(hparams, MINDIterator, seed=seed)

group_impr_indexes, group_labels, group_preds = model.run_fast_eval(test_news_file, test_behaviors_file)
```


But this time, another unexpected error happened:

```bash
0it [00:00, ?it/s]/usr/local/lib/python3.7/dist-packages/keras/engine/training_v1.py:2079: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  updates=self.state_updates,
3781it [00:15, 239.15it/s]
0it [00:00, ?it/s]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-13-b1bb328ce75e>](https://localhost:8080/#) in <module>()
----> 1 group_impr_indexes, group_labels, group_preds = model.run_fast_eval(test_news_file, test_behaviors_file)

5 frames
[/usr/local/lib/python3.7/dist-packages/recommenders/models/newsrec/io/mind_iterator.py](https://localhost:8080/#) in <listcomp>(.0)
    124 
    125                 impr_news = [self.nid2index[i.split("-")[0]] for i in impr.split()]
--> 126                 label = [int(i.split("-")[1]) for i in impr.split()]
    127                 uindex = self.uid2index[uid] if uid in self.uid2index else 0
    128 

IndexError: list index out of range
```

Do you have any insight into the possible cause? 
I suppose the model can generate the predictions without actual training so I skipped the training phase.

All the code are copied from  `nrms_MIND.ipynb` and run on the google colab. Envrionment:

```bash
System version: 3.7.12 (default, Jan 15 2022, 18:48:18) 
[GCC 7.5.0]
Tensorflow version: 2.8.0
```

Here is the colab notebook you can see the actual error message:
- https://colab.research.google.com/drive/1q-RFcROkTNhkvpohft1UiJfbiNzTbEjw?usp=sharing

Any suggestion is highly appreciated 🙏

**Comment by yjw1029** [comment]
@leemengtaiwan 
The validation code does not support the format of test dataset, which does not contain label information. Please change the code in recommenders/models/newsrec/io/mind_interator.py init_behaviors (line 103) to 
```python
def init_behaviors(self, behaviors_file):
        """init behavior logs given behaviors file.

        Args:
        behaviors_file: path of behaviors file
        """
        self.histories = []
        self.imprs = []
        self.labels = []
        self.impr_indexes = []
        self.uindexes = []
        test_mode = False

        with tf.io.gfile.GFile(behaviors_file, "r") as rd:
            impr_index = 0
            for line in rd:
                uid, time, history, impr = line.strip("\n").split(self.col_spliter)[-4:]

                history = [self.nid2index[i] for i in history.split()]
                history = [0] * (self.his_size - len(history)) + history[
                    : self.his_size
                ]

                impr_news = [self.nid2index[i.split("-")[0]] for i in impr.split()]

                try:
                    if not test_mode:
                        label = [int(i.split("-")[1]) for i in impr.split()]
                    else:
                        label = [0 for i in impr.split()]
                except:
                    test_mode = True
                    label = [0 for i in impr.split()]

                uindex = self.uid2index[uid] if uid in self.uid2index else 0

                self.histories.append(history)
                self.imprs.append(impr_news)
                self.labels.append(label)
                self.impr_indexes.append(impr_index)
                self.uindexes.append(uindex)
                impr_index += 1
```
And reinstall recommenders
```bash
cd recommenders
pip install -e .
```
Meanwhile, if you have run `run_eval` on validation set before `run_fast_eval` on test set, please init the news and behavior information again before `run_fast_eval` to remove the news and behavior information of validation dataset.
```
model.test_iterator.init_news(test_news_file)
model.test_iterator.init_behaviors(test_behaviors_file)
group_impr_indexes, group_labels, group_preds = model.run_fast_eval(test_news_file, test_behaviors_file)
```

**Comment by leemengtaiwan** [comment]
@yjw1029 
I successfully uploaded and got the score, thank you so much!

**Comment by ubergonmx** [comment]
The following code: 
```python
label = [0 for i in impr.split()]
```
is essentially making each news ID in the impression list non-clicked if I understand it correctly (e.g., `N712-0 N231-0`).

Instead of modifying the code, I modified the test behaviors file and added `-0` to each news ID in the impression list.
Now I get the following error after running `run_eval`:
```python
model.run_eval(test_news_file, test_behaviors_file)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File <timed exec>:1

File ~/.conda/envs/recommenders/lib/python3.9/site-packages/recommenders/models/newsrec/models/base_model.py:335, in BaseModel.run_eval(self, news_filename, behaviors_file)
    331 else:
    332     _, group_labels, group_preds = self.run_slow_eval(
    333         news_filename, behaviors_file
    334     )
--> 335 res = cal_metric(group_labels, group_preds, self.hparams.metrics)
    336 return res

File ~/.conda/envs/recommenders/lib/python3.9/site-packages/recommenders/models/deeprec/deeprec_utils.py:594, in cal_metric(labels, preds, metrics)
    591         res["hit@{0}".format(k)] = round(hit_temp, 4)
    592 elif metric == "group_auc":
    593     group_auc = np.mean(
--> 594         [
    595             roc_auc_score(each_labels, each_preds)
    596             for each_labels, each_preds in zip(labels, preds)
    597         ]
    598     )
    599     res["group_auc"] = round(group_auc, 4)
    600 else:

File ~/.conda/envs/recommenders/lib/python3.9/site-packages/recommenders/models/deeprec/deeprec_utils.py:595, in <listcomp>(.0)
    591         res["hit@{0}".format(k)] = round(hit_temp, 4)
    592 elif metric == "group_auc":
    593     group_auc = np.mean(
    594         [
--> 595             roc_auc_score(each_labels, each_preds)
    596             for each_labels, each_preds in zip(labels, preds)
    597         ]
    598     )
    599     res["group_auc"] = round(group_auc, 4)
    600 else:

File ~/.conda/envs/recommenders/lib/python3.9/site-packages/sklearn/metrics/_ranking.py:567, in roc_auc_score(y_true, y_score, average, sample_weight, max_fpr, multi_class, labels)
    565     labels = np.unique(y_true)
    566     y_true = label_binarize(y_true, classes=labels)[:, 0]
--> 567     return _average_binary_score(
    568         partial(_binary_roc_auc_score, max_fpr=max_fpr),
    569         y_true,
    570         y_score,
    571         average,
    572         sample_weight=sample_weight,
    573     )
    574 else:  # multilabel-indicator
    575     return _average_binary_score(
    576         partial(_binary_roc_auc_score, max_fpr=max_fpr),
    577         y_true,
   (...)
    580         sample_weight=sample_weight,
    581     )

File ~/.conda/envs/recommenders/lib/python3.9/site-packages/sklearn/metrics/_base.py:75, in _average_binary_score(binary_metric, y_true, y_score, average, sample_weight)
     72     raise ValueError("{0} format is not supported".format(y_type))
     74 if y_type == "binary":
---> 75     return binary_metric(y_true, y_score, sample_weight=sample_weight)
     77 check_consistent_length(y_true, y_score, sample_weight)
     78 y_true = check_array(y_true)

File ~/.conda/envs/recommenders/lib/python3.9/site-packages/sklearn/metrics/_ranking.py:337, in _binary_roc_auc_score(y_true, y_score, sample_weight, max_fpr)
    335 """Binary roc auc score."""
    336 if len(np.unique(y_true)) != 2:
--> 337     raise ValueError(
    338         "Only one class present in y_true. ROC AUC score "
    339         "is not defined in that case."
    340     )
    342 fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
    343 if max_fpr is None or max_fpr == 1:

ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
```

Any fix to this?
