### ISSUE TITLE
[BUG] Problem with documentation

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#1689]
### In which platform does it happen?

In readthedocs

### How do we replicate the issue?

Error:
```
Running Sphinx v1.8.6
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/staging/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/staging/lib/python3.7/site-packages/sphinx/builders/latex/__init__.py", line 37, in <module>
    from sphinx.writers.latex import DEFAULT_SETTINGS, LaTeXWriter, LaTeXTranslator
  File "/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/staging/lib/python3.7/site-packages/sphinx/writers/latex.py", line 33, in <module>
    from sphinx.util.template import LaTeXRenderer
  File "/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/staging/lib/python3.7/site-packages/sphinx/util/template.py", line 17, in <module>
    from sphinx.jinja2glue import SphinxFileSystemLoader
  File "/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/staging/lib/python3.7/site-packages/sphinx/jinja2glue.py", line 16, in <module>
    from jinja2 import FileSystemLoader, BaseLoader, TemplateNotFound, \
ImportError: cannot import name 'contextfunction' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/staging/lib/python3.7/site-packages/jinja2/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/staging/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/staging/lib/python3.7/site-packages/sphinx/application.py", line 224, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/staging/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/staging/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinx.builders.latex (exception: cannot import name 'contextfunction' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/staging/lib/python3.7/site-packages/jinja2/__init__.py))

Extension error:
Could not import extension sphinx.builders.latex (exception: cannot import name 'contextfunction' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/microsoft-recommenders/envs/staging/lib/python3.7/site-packages/jinja2/__init__.py))

```

**Comment by miguelgfierro** [comment]
It seems like an issue with jinja2 version https://github.com/readthedocs/readthedocs.org/issues/9038
