### ISSUE TITLE
[BUG] AttributeError: 'dict' object has no attribute '__LIGHTFM_SETUP__'

### ISSUE THREAD

**Issue by benoit360l** [microsoft/recommenders#1930]
### Description

My CICD is failing when installing recommenders. Previously this code was working correctly. 

Full stacktrace :  
```
9s
Run python -m pip install --upgrade pip
Requirement already satisfied: pip in /opt/hostedtoolcache/Python/3.8.[1](https://github.com/360Learning/course-recommendations/actions/runs/5044258746/jobs/9047069712?pr=337#step:4:1)6/x64/lib/python3.8/site-packages (22.0.4)
Collecting pip
  Downloading pip-23.1.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 11.2 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-23.1.2
Collecting pytest
  Downloading pytest-7.3.1-py3-none-any.whl (320 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.5/320.5 kB 9.5 MB/s eta 0:00:00
Collecting iniconfig (from pytest)
  Downloading iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting packaging (from pytest)
  Downloading packaging-23.1-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 16.7 MB/s eta 0:00:00
Collecting pluggy<2.0,>=0.12 (from pytest)
  Downloading pluggy-1.0.0-py2.py3-none-any.whl ([13](https://github.com/360Learning/course-recommendations/actions/runs/5044258746/jobs/9047069712?pr=337#step:4:14) kB)
Collecting exceptiongroup>=1.0.0rc8 (from pytest)
  Downloading exceptiongroup-1.1.1-py3-none-any.whl ([14](https://github.com/360Learning/course-recommendations/actions/runs/5044258746/jobs/9047069712?pr=337#step:4:15) kB)
Collecting tomli>=1.0.0 (from pytest)
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Installing collected packages: tomli, pluggy, packaging, iniconfig, exceptiongroup, pytest
Successfully installed exceptiongroup-1.1.1 iniconfig-2.0.0 packaging-23.1 pluggy-1.0.0 pytest-7.3.1 tomli-2.0.1
Collecting recommenders==1.1.1 (from -r requirements.txt (line 1))
  Downloading recommenders-1.1.1-py3-none-any.whl (339 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 339.0/339.0 kB 7.3 MB/s eta 0:00:00
Collecting numpy>=1.19 (from recommenders==1.1.1->-r requirements.txt (line 1))
  Downloading numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 69.9 MB/s eta 0:00:00
Collecting pandas<2,>1.0.3 (from recommenders==1.1.1->-r requirements.txt (line 1))
  Downloading pandas-1.5.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 111.9 MB/s eta 0:00:00
Collecting scipy<2,>=1.0.0 (from recommenders==1.1.1->-r requirements.txt (line 1))
  Downloading scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.5/34.5 MB 64.0 MB/s eta 0:00:00
Collecting tqdm<5,>=4.31.1 (from recommenders==1.1.1->-r requirements.txt (line 1))
  Downloading tqdm-4.65.0-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 27.5 MB/s eta 0:00:00
Collecting matplotlib<4,>=2.2.2 (from recommenders==1.1.1->-r requirements.txt (line 1))
  Downloading matplotlib-3.7.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 125.1 MB/s eta 0:00:00
Collecting scikit-learn<1.0.3,>=0.22.1 (from recommenders==1.1.1->-r requirements.txt (line 1))
  Downloading scikit_learn-1.0.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 62.5 MB/s eta 0:00:00
Collecting numba<1,>=0.38.1 (from recommenders==1.1.1->-r requirements.txt (line 1))
  Downloading numba-0.57.0-cp38-cp38-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 77.6 MB/s eta 0:00:00
Collecting lightfm<2,>=1.[15](https://github.com/360Learning/course-recommendations/actions/runs/5044258746/jobs/9047069712?pr=337#step:4:16) (from recommenders==1.1.1->-r requirements.txt (line 1))
  Downloading lightfm-1.17.tar.gz (3[16](https://github.com/360Learning/course-recommendations/actions/runs/5044258746/jobs/9047069712?pr=337#step:4:17) kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.4/316.4 kB 69.7 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [[17](https://github.com/360Learning/course-recommendations/actions/runs/5044258746/jobs/9047069712?pr=337#step:4:18) lines of output]
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 1[18](https://github.com/360Learning/course-recommendations/actions/runs/5044258746/jobs/9047069712?pr=337#step:4:19), in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-_9_g7ize/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-_9_g7ize/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 3[23](https://github.com/360Learning/course-recommendations/actions/runs/5044258746/jobs/9047069712?pr=337#step:4:24), in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-_9_g7ize/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-_9_g7ize/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line [33](https://github.com/360Learning/course-recommendations/actions/runs/5044258746/jobs/9047069712?pr=337#step:4:34)8, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      AttributeError: 'dict' object has no attribute '__LIGHTFM_SETUP__'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

### In which platform does it happen?

Github Actions CICD : 
```
name: Run Python Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests with pytest
        run: |
          pytest

```

requirements.txt : 
```
recommenders==1.1.1
```

**Comment by benoit360l** [comment]
It's a lightFM related issue : https://github.com/lyst/lightfm/issues/687
I don't think there is something to perform on this repo.

**Comment by yefetBenTili** [comment]
I know it Lightfm issue but were you able to solve this for Lightfm?

**Comment by AndreasKarasenko** [comment]
The link above essentially boils down to:
`python -m pip install --upgrade pip setuptools wheel`
