### ISSUE TITLE
[BUG] Issue with AzureML machines in tests. Conflict of Cornac with NumPy

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#1933]
### Description

Machines are not starting, so no tests are being triggered.

### In which platform does it happen?

AzureML

### How do we replicate the issue?

by triggering the tests
```
"error": ***
        "message": "Activity Failed:\n***\n    \"error\": ***\n        \"code\": \"UserError\",\n        \"message\": \"Image build failed. For more details, check log file azureml-logs/20_image_build_log.txt.\",\n        \"messageFormat\": \"Image build failed. For more details, check log file ***ArtifactPath***.\",\n        \"messageParameters\": ***\n            \"ArtifactPath\": \"azureml-logs/20_image_build_log.txt\"\n        ***,\n        \"details\": [],\n        \"innerError\": ***\n            \"code\": \"BadArgument\",\n            \"innerError\": ***\n                \"code\": \"ImageBuildFailure\"\n            ***\n        ***\n    ***,\n    \"correlation\": ***\n        \"operation\": \"9e89362ac8454ae436aebd9cdc824dc8\",\n        \"request\": \"1417867f9fdf05be\"\n    ***,\n    \"environment\": \"eastus\",\n    \"location\": \"eastus\",\n    \"time\": \"2023-06-01T00:18:06.477534Z\",\n    \"componentName\": \"RunHistory\"\n***"
```

### Other Comments
See logs: https://github.com/microsoft/recommenders/actions/runs/5138848873/jobs/9248618895

**Comment by miguelgfierro** [comment]
Log in 20_image_build_log.txt:

```
2023/06/01 00:07:50 Downloading source code...
2023/06/01 00:07:51 Finished downloading source code
2023/06/01 00:07:51 Creating Docker network: acb_default_network, driver: 'bridge'
2023/06/01 00:07:52 Successfully set up Docker network: acb_default_network
2023/06/01 00:07:52 Setting up Docker configuration...
2023/06/01 00:07:52 Successfully set up Docker configuration
2023/06/01 00:07:52 Logging in to registry: 978a92daa2ad4447aae1b21196dd4a9b.azurecr.io
2023/06/01 00:07:53 Successfully logged into 978a92daa2ad4447aae1b21196dd4a9b.azurecr.io
2023/06/01 00:07:53 Executing step ID: acb_step_0. Timeout(sec): 5400, Working directory: '', Network: 'acb_default_network'
2023/06/01 00:07:53 Scanning for dependencies...
2023/06/01 00:07:53 Successfully scanned dependencies
2023/06/01 00:07:53 Launching container with name: acb_step_0
Sending build context to Docker daemon  71.68kB

Step 1/21 : FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20230509.v1@sha256:21a5aff01e75574d94cd25802026a9ac5be1936dc2afe2973537f2c47abd4bc5
mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20230509.v1@sha256:21a5aff01e75574d94cd25802026a9ac5be1936dc2afe2973537f2c47abd4bc5: Pulling from azureml/openmpi4.1.0-ubuntu20.04
Digest: sha256:21a5aff01e75574d94cd25802026a9ac5be1936dc2afe2973537f2c47abd4bc5
Status: Downloaded newer image for mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20230509.v1@sha256:21a5aff01e75574d94cd25802026a9ac5be1936dc2afe2973537f2c47abd4bc5
 ---> cc73fcec3204
Step 2/21 : USER root
 ---> Running in 98093c88c852
Removing intermediate container 98093c88c852
 ---> 30d1807ea6c0
Step 3/21 : RUN mkdir -p $HOME/.cache
 ---> Running in ca16a4fa1b32
Removing intermediate container ca16a4fa1b32
 ---> 1c9b45acc42e
Step 4/21 : WORKDIR /
 ---> Running in e8220f79372d
Removing intermediate container e8220f79372d
 ---> e89a7d6bf613
Step 5/21 : COPY azureml-environment-setup/99brokenproxy /etc/apt/apt.conf.d/
 ---> 9212307e14a2
Step 6/21 : RUN if dpkg --compare-versions `conda --version | grep -oE '[^ ]+$'` lt 4.4.11; then conda install conda==4.4.11; fi
 ---> Running in d6b609263e89
Removing intermediate container d6b609263e89
 ---> eb09a850a8a4
Step 7/21 : COPY azureml-environment-setup/mutated_conda_dependencies.yml azureml-environment-setup/mutated_conda_dependencies.yml
 ---> a11387800b72
Step 8/21 : RUN ldconfig /usr/local/cuda/lib64/stubs && conda env create -p /azureml-envs/azureml_362c648550ddf3444cbaf086714b5547 -f azureml-environment-setup/mutated_conda_dependencies.yml && rm -rf "$HOME/.cache/pip" && conda clean -aqy && CONDA_ROOT_DIR=$(conda info --root) && rm -rf "$CONDA_ROOT_DIR/pkgs" && find "$CONDA_ROOT_DIR" -type d -name __pycache__ -exec rm -rf {} + && ldconfig
 ---> Running in 1bcfa41871ab
Retrieving notices: ...working... done
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): ...working... 
done
Solving environment: ...working... done

Downloading and Extracting Packages
[91m

==> WARNING: A newer version of conda exists. <==
  current version: 23.3.1
  latest version: 23.5.0

Please update conda by running

    $ conda update -n base -c conda-forge conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.5.0


[0m
readline-8.2         | 457 KB    |            |   0% 

openssl-1.1.1s       | 3.8 MB    |            |   0% [A


tk-8.6.12            | 3.3 MB    |            |   0% [A[A



ld_impl_linux-64-2.3 | 732 KB    |            |   0% [A[A[A




_openmp_mutex-5.1    | 20 KB     |            |   0% [A[A[A[A





libgcc-ng-11.2.0     | 8.5 MB    |            |   0% [A[A[A[A[A






zlib-1.2.13          | 125 KB    |            |   0% [A[A[A[A[A[A







wheel-0.37.1         | 31 KB     |            |   0% [A[A[A[A[A[A[A








xz-5.2.10            | 449 KB    |            |   0% [A[A[A[A[A[A[A[A









libgomp-11.2.0       | 560 KB    |            |   0% [A[A[A[A[A[A[A[A[A










certifi-2022.12.7    | 152 KB    |            |   0% [A[A[A[A[A[A[A[A[A[A











_libgcc_mutex-0.1    | 3 KB      |            |   0% [A[A[A[A[A[A[A[A[A[A[A












sqlite-3.40.1        | 1.6 MB    |            |   0% [A[A[A[A[A[A[A[A[A[A[A[A













ca-certificates-2023 | 127 KB    |            |   0% [A[A[A[A[A[A[A[A[A[A[A[A[A














pip-22.3.1           | 2.7 MB    |            |   0% [A[A[A[A[A[A[A[A[A[A[A[A[A[A















ncurses-6.4          | 1.1 MB    |            |   0% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A
















libstdcxx-ng-11.2.0  | 6.1 MB    |            |   0% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A

















libffi-3.4.2         | 135 KB    |            |   0% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A


















python-3.7.16        | 46.5 MB   |            |   0% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A



















 ... (more hidden) ...[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A
readline-8.2         | 457 KB    | #7         |  18% 

openssl-1.1.1s       | 3.8 MB    | 1          |   2% [A


tk-8.6.12            | 3.3 MB    | 3          |   3% [A[A



ld_impl_linux-64-2.3 | 732 KB    | 2          |   2% [A[A[A




_openmp_mutex-5.1    | 20 KB     | #######8   |  79% [A[A[A[A


tk-8.6.12            | 3.3 MB    | #8         |  19% [A[A

openssl-1.1.1s       | 3.8 MB    | #          |  10% [A





libgcc-ng-11.2.0     | 8.5 MB    |            |   0% [A[A[A[A[A



ld_impl_linux-64-2.3 | 732 KB    | #5         |  15% [A[A[A
readline-8.2         | 457 KB    | ########## | 100% 






zlib-1.2.13          | 125 KB    | #2         |  13% [A[A[A[A[A[A
readline-8.2         | 457 KB    | ########## | 100% 




_openmp_mutex-5.1    | 20 KB     | ########## | 100% [A[A[A[A







wheel-0.37.1         | 31 KB     | #####1     |  52% [A[A[A[A[A[A[A


tk-8.6.12            | 3.3 MB    | #####1     |  52% [A[A





libgcc-ng-11.2.0     | 8.5 MB    | #          |  10% [A[A[A[A[A

openssl-1.1.1s       | 3.8 MB    | ###6       |  37% [A






zlib-1.2.13          | 125 KB    | ########## | 100% [A[A[A[A[A[A








xz-5.2.10            | 449 KB    | 3          |   4% [A[A[A[A[A[A[A[A









libgomp-11.2.0       | 560 KB    | 2          |   3% [A[A[A[A[A[A[A[A[A







wheel-0.37.1         | 31 KB     | ########## | 100% [A[A[A[A[A[A[A





libgcc-ng-11.2.0     | 8.5 MB    | #6         |  17% [A[A[A[A[A

openssl-1.1.1s       | 3.8 MB    | #####3     |  53% [A








xz-5.2.10            | 449 KB    | ########2  |  82% [A[A[A[A[A[A[A[A









libgomp-11.2.0       | 560 KB    | #######1   |  71% [A[A[A[A[A[A[A[A[A


tk-8.6.12            | 3.3 MB    | #######    |  71% [A[A



ld_impl_linux-64-2.3 | 732 KB    | ########## | 100% [A[A[A



ld_impl_linux-64-2.3 | 732 KB    | ########## | 100% [A[A[A










certifi-2022.12.7    | 152 KB    | #          |  11% [A[A[A[A[A[A[A[A[A[A











_libgcc_mutex-0.1    | 3 KB      | ########## | 100% [A[A[A[A[A[A[A[A[A[A[A





libgcc-ng-11.2.0     | 8.5 MB    | ##1        |  22% [A[A[A[A[A

openssl-1.1.1s       | 3.8 MB    | ######6    |  66% [A


tk-8.6.12            | 3.3 MB    | ########6  |  86% [A[A












sqlite-3.40.1        | 1.6 MB    | 1          |   1% [A[A[A[A[A[A[A[A[A[A[A[A













ca-certificates-2023 | 127 KB    | #2         |  13% [A[A[A[A[A[A[A[A[A[A[A[A[A








xz-5.2.10            | 449 KB    | ########## | 100% [A[A[A[A[A[A[A[A





libgcc-ng-11.2.0     | 8.5 MB    | ###3       |  33% [A[A[A[A[A












sqlite-3.40.1        | 1.6 MB    | #########9 | 100% [A[A[A[A[A[A[A[A[A[A[A[A














pip-22.3.1           | 2.7 MB    |            |   1% [A[A[A[A[A[A[A[A[A[A[A[A[A[A















ncurses-6.4          | 1.1 MB    | 1          |   1% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A

openssl-1.1.1s       | 3.8 MB    | ########9  |  89% [A









libgomp-11.2.0       | 560 KB    | ########## | 100% [A[A[A[A[A[A[A[A[A
















libstdcxx-ng-11.2.0  | 6.1 MB    |            |   0% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A










certifi-2022.12.7    | 152 KB    | ########## | 100% [A[A[A[A[A[A[A[A[A[A










certifi-2022.12.7    | 152 KB    | ########## | 100% [A[A[A[A[A[A[A[A[A[A











_libgcc_mutex-0.1    | 3 KB      | ########## | 100% [A[A[A[A[A[A[A[A[A[A[A





libgcc-ng-11.2.0     | 8.5 MB    | ####       |  40% [A[A[A[A[A














pip-22.3.1           | 2.7 MB    | ###2       |  32% [A[A[A[A[A[A[A[A[A[A[A[A[A[A















ncurses-6.4          | 1.1 MB    | #######    |  71% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A













ca-certificates-2023 | 127 KB    | ########## | 100% [A[A[A[A[A[A[A[A[A[A[A[A[A













ca-certificates-2023 | 127 KB    | ########## | 100% [A[A[A[A[A[A[A[A[A[A[A[A[A

















libffi-3.4.2         | 135 KB    | #1         |  12% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A
















libstdcxx-ng-11.2.0  | 6.1 MB    | #2         |  12% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A





libgcc-ng-11.2.0     | 8.5 MB    | ####6      |  47% [A[A[A[A[A


















python-3.7.16        | 46.5 MB   |            |   0% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A














pip-22.3.1           | 2.7 MB    | #####      |  51% [A[A[A[A[A[A[A[A[A[A[A[A[A[A



















 ... (more hidden) ...[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A
















libstdcxx-ng-11.2.0  | 6.1 MB    | ###        |  31% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A


tk-8.6.12            | 3.3 MB    | ########## | 100% [A[A














pip-22.3.1           | 2.7 MB    | #########  |  91% [A[A[A[A[A[A[A[A[A[A[A[A[A[A


















python-3.7.16        | 46.5 MB   | 5          |   5% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A



















 ... (more hidden) ...[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A





libgcc-ng-11.2.0     | 8.5 MB    | ######2    |  63% [A[A[A[A[A












sqlite-3.40.1        | 1.6 MB    | ########## | 100% [A[A[A[A[A[A[A[A[A[A[A[A
















libstdcxx-ng-11.2.0  | 6.1 MB    | ####       |  40% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A



















 ... (more hidden) ...[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A





libgcc-ng-11.2.0     | 8.5 MB    | ######8    |  68% [A[A[A[A[A


















python-3.7.16        | 46.5 MB   | 6          |   6% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A

openssl-1.1.1s       | 3.8 MB    | ########## | 100% [A
















libstdcxx-ng-11.2.0  | 6.1 MB    | ####7      |  48% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A

















libffi-3.4.2         | 135 KB    | ########## | 100% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A

















libffi-3.4.2         | 135 KB    | ########## | 100% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A


















python-3.7.16        | 46.5 MB   | 8          |   8% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A





libgcc-ng-11.2.0     | 8.5 MB    | #######8   |  79% [A[A[A[A[A
















libstdcxx-ng-11.2.0  | 6.1 MB    | ######1    |  62% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A


















python-3.7.16        | 46.5 MB   | #3         |  13% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A
















libstdcxx-ng-11.2.0  | 6.1 MB    | #########7 |  97% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A















ncurses-6.4          | 1.1 MB    | ########## | 100% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A


















python-3.7.16        | 46.5 MB   | ##2        |  22% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A














pip-22.3.1           | 2.7 MB    | ########## | 100% [A[A[A[A[A[A[A[A[A[A[A[A[A[A


















python-3.7.16        | 46.5 MB   | ###        |  30% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A



















 ... (more hidden) ...[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A


















python-3.7.16        | 46.5 MB   | ###3       |  34% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A





libgcc-ng-11.2.0     | 8.5 MB    | ########## | 100% [A[A[A[A[A





libgcc-ng-11.2.0     | 8.5 MB    | ########## | 100% [A[A[A[A[A
















libstdcxx-ng-11.2.0  | 6.1 MB    | ########## | 100% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A


















python-3.7.16        | 46.5 MB   | ###5       |  35% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A


















python-3.7.16        | 46.5 MB   | ######4    |  65% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A


















python-3.7.16        | 46.5 MB   | #######4   |  74% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A


















python-3.7.16        | 46.5 MB   | #########8 |  99% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A


















python-3.7.16        | 46.5 MB   | ########## | 100% [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A



















                      
[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A
                                                     

                                                     [A


                                                     [A[A



                                                     [A[A[A




                                                     [A[A[A[A





                                                     [A[A[A[A[A






                                                     [A[A[A[A[A[A







                                                     [A[A[A[A[A[A[A








                                                     [A[A[A[A[A[A[A[A









                                                     [A[A[A[A[A[A[A[A[A










                                                     [A[A[A[A[A[A[A[A[A[A











                                                     [A[A[A[A[A[A[A[A[A[A[A












                                                     [A[A[A[A[A[A[A[A[A[A[A[A













                                                     [A[A[A[A[A[A[A[A[A[A[A[A[A














                                                     [A[A[A[A[A[A[A[A[A[A[A[A[A[A















                                                     [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A
















                                                     [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A

















                                                     [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A


















                                                     [A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Installing pip dependencies: ...working... Ran pip subprocess with arguments:
['/azureml-envs/azureml_362c648550ddf3444cbaf086714b5547/bin/python', '-m', 'pip', 'install', '-U', '-r', '/azureml-environment-setup/condaenv.3uxcof47.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting pymanopt@ https://github.com/pymanopt/pymanopt/archive/fb36a272cdeecb21992cfd9271eb82baafeb316d.zip
  Downloading https://github.com/pymanopt/pymanopt/archive/fb36a272cdeecb21992cfd9271eb82baafeb316d.zip
     - 215.5 kB 6.8 MB/s 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting azureml-defaults
  Downloading azureml_defaults-1.51.0-py3-none-any.whl (2.0 kB)
Collecting recommenders[dev,examples]
  Downloading recommenders-1.1.1-py3-none-any.whl (339 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 339.0/339.0 kB 36.0 MB/s eta 0:00:00
Collecting azureml-dataset-runtime[fuse]~=1.51.0
  Downloading azureml_dataset_runtime-1.51.0-py3-none-any.whl (2.3 kB)
Collecting azureml-inference-server-http~=0.8.0
  Downloading azureml_inference_server_http-0.8.4-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.4/58.4 kB 12.1 MB/s eta 0:00:00
Collecting azureml-core~=1.51.0
  Downloading azureml_core-1.51.0-py3-none-any.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 109.7 MB/s eta 0:00:00
Collecting numpy>=1.16
  Downloading numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 98.2 MB/s eta 0:00:00
Collecting scipy
  Downloading scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.1/38.1 MB 41.6 MB/s eta 0:00:00
Collecting lightgbm>=2.2.1
  Downloading lightgbm-3.3.5-py3-none-manylinux1_x86_64.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 104.6 MB/s eta 0:00:00
Collecting lightfm<2,>=1.15
  Downloading lightfm-1.17.tar.gz (316 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.4/316.4 kB 28.9 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting seaborn<1,>=0.8.1
  Downloading seaborn-0.12.2-py3-none-any.whl (293 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.3/293.3 kB 48.9 MB/s eta 0:00:00
Collecting scikit-learn<1.0.3,>=0.22.1
  Downloading scikit_learn-1.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.8/24.8 MB 79.3 MB/s eta 0:00:00
Collecting retrying>=1.3.3
  Downloading retrying-1.3.4-py3-none-any.whl (11 kB)
Collecting pandera[strategies]>=0.6.5
  Downloading pandera-0.15.1-py3-none-any.whl (152 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.4/152.4 kB 28.2 MB/s eta 0:00:00
Collecting tqdm<5,>=4.31.1
  Downloading tqdm-4.65.0-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 12.5 MB/s eta 0:00:00
Collecting jinja2<3.1,>=2
  Downloading Jinja2-3.0.3-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.6/133.6 kB 12.1 MB/s eta 0:00:00
Collecting cornac<2,>=1.1.2
  Downloading cornac-1.15.4.tar.gz (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 106.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

failed
[91mPip subprocess error:
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-1kntvdao/cornac_d3bf5705ee214047ad213955b1135de2/setup.py", line 32, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


CondaEnvException: Pip failed

[0mThe command '/bin/sh -c ldconfig /usr/local/cuda/lib64/stubs && conda env create -p /azureml-envs/azureml_362c648550ddf3444cbaf086714b5547 -f azureml-environment-setup/mutated_conda_dependencies.yml && rm -rf "$HOME/.cache/pip" && conda clean -aqy && CONDA_ROOT_DIR=$(conda info --root) && rm -rf "$CONDA_ROOT_DIR/pkgs" && find "$CONDA_ROOT_DIR" -type d -name __pycache__ -exec rm -rf {} + && ldconfig' returned a non-zero code: 1
2023/06/01 00:10:17 Container failed during run: acb_step_0. No retries remaining.
failed to run step ID: acb_step_0: exit status 1

Run ID: ca1v failed after 2m28s. Error: failed during run, err: exit status 1


```

**Comment by miguelgfierro** [comment]
The error comes from cornac conflict with numpy:
```
$ pip install .[dev,examples]
Processing /home/miguel/MS/recommenders
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting category-encoders<2,>=1.3.0
  Using cached category_encoders-1.3.0-py2.py3-none-any.whl (61 kB)
Collecting nltk<4,>=3.4
  Downloading nltk-3.8.1-py3-none-any.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 6.2 MB/s eta 0:00:00
Collecting retrying>=1.3.3
  Using cached retrying-1.3.4-py3-none-any.whl (11 kB)
Collecting scikit-surprise>=1.0.6
  Using cached scikit-surprise-1.1.1.tar.gz (11.8 MB)
  Preparing metadata (setup.py) ... done
Collecting tqdm<5,>=4.31.1
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting scipy<2,>=1.0.0
  Using cached scipy-1.7.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (38.1 MB)
Collecting lightfm<2,>=1.15
  Downloading lightfm-1.17.tar.gz (316 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.4/316.4 kB 21.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting bottleneck<2,>=1.2.1
  Downloading Bottleneck-1.3.7-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (355 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 355.9/355.9 kB 15.8 MB/s eta 0:00:00
Collecting scrapbook<1.0.0,>=0.5.0
  Using cached scrapbook-0.5.0-py3-none-any.whl (34 kB)
Collecting matplotlib<4,>=2.2.2
  Downloading matplotlib-3.5.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 6.7 MB/s eta 0:00:00
Collecting seaborn<1,>=0.8.1
  Downloading seaborn-0.12.2-py3-none-any.whl (293 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.3/293.3 kB 7.5 MB/s eta 0:00:00
Collecting memory-profiler<1,>=0.54.0
  Using cached memory_profiler-0.61.0-py3-none-any.whl (31 kB)
Collecting pandera[strategies]>=0.6.5
  Downloading pandera-0.15.1-py3-none-any.whl (152 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.4/152.4 kB 5.8 MB/s eta 0:00:00
Collecting scikit-learn<1.0.3,>=0.22.1
  Using cached scikit_learn-1.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (24.8 MB)
Collecting cornac<2,>=1.1.2
  Downloading cornac-1.15.4.tar.gz (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 4.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7opbx3e3/cornac_1903b716b8844efda3126866cf81bc3d/setup.py", line 32, in <module>
          import numpy as np
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by miguelgfierro** [comment]
There is a conflict with the latest cornac 1.15.4

cornac-1.15.1 -> works

hey @tqtg, I think you guys have a problem with 1.15.4, the setup.py gets hung out: `Building wheel for cornac (setup.py) ...`

I'm going to restrict cornac to 1.15.1 in the deps for the moment. If you find the issue, let me know.

**Comment by tqtg** [comment]
Hey @miguelgfierro, thanks for raising the attention. Restricting cornac to 1.15.1 should be fine.

Regarding the issue, we have decided to support Python 3.8 onwards so there are no pre-built wheel files for Python 3.7. To build from source, you might need to reinstall `setuptools` in order for it to detect `numpy` properly. We faced similar issue recently on Azure envs. Hope it helps!
