### ISSUE TITLE
[BUG] Wide and Deep: Feature not in features dictionary

### ISSUE THREAD

**Issue by ajhepburn** [Microsoft/Recommenders#668]
I am following the Wide and Deep notebook and have a Pandas DataFrame of the following format for input:

```
  user_id  item_id    target                                      item_features
0   406225     7271  0.041523  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1   406225     1183  0.000143  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2   406225     5930  0.011455  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3   406225     7162  0.001289  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4   406225     7789  0.002005  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
```

I get to about the 4th or 5th step when the model training crashes as it claims `item_features` is not in the features dictionary. I'm not sure if I've missed something. Happy to supply any more details.

```
INFO:tensorflow:Saving checkpoints for 0 into ./models/widedeep/model.ckpt.
INFO:tensorflow:loss = 170.29544, step = 0
INFO:tensorflow:global_step/sec: 204.513
INFO:tensorflow:loss = 0.25550294, step = 921 (4.503 sec)
INFO:tensorflow:global_step/sec: 196.912
INFO:tensorflow:loss = 0.0111105675, step = 1842 (4.677 sec)
INFO:tensorflow:global_step/sec: 198.757
INFO:tensorflow:loss = 0.043361906, step = 2763 (4.634 sec)
INFO:tensorflow:Saving checkpoints for 3685 into ./models/widedeep/model.ckpt.
INFO:tensorflow:global_step/sec: 185.382
INFO:tensorflow:loss = 0.20295088, step = 3684 (4.968 sec)
Traceback (most recent call last):
  File "model_wide_deep.py", line 293, in <module>
    wdm.run()
  File "model_wide_deep.py", line 288, in run
    self.train_and_eval(model, data_splits, user_item_info, steps)
  File "model_wide_deep.py", line 263, in train_and_eval
    steps=train_steps
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1241, in _train_model_default
    saving_listeners)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1471, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1320, in run
    run_metadata=run_metadata))
  File "/media/ntfs/Workspace/Project/rec-sys/reco_utils/common/tf_utils.py", line 234, in after_run
    len(self.eval_df)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 577, in predict
    features, None, model_fn_lib.ModeKeys.PREDICT, self.config)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/estimator/canned/dnn_linear_combined.py", line 628, in _model_fn
    linear_sparse_combiner=linear_sparse_combiner)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/estimator/canned/dnn_linear_combined.py", line 179, in _dnn_linear_combined_model_fn
    dnn_logits = dnn_logit_fn(features=features, mode=mode)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/estimator/canned/dnn.py", line 109, in dnn_logit_fn
    return dnn_model(features, mode)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 757, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/estimator/canned/dnn.py", line 204, in call
    net = self._input_layer(features)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column.py", line 333, in __call__
    from_template=True)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 368, in __call__
    return self._call_func(args, kwargs)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 311, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column.py", line 222, in _internal_input_layer
    return _get_logits()
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column.py", line 201, in _get_logits
    trainable=trainable)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column.py", line 2500, in _get_dense_tensor
    return inputs.get(self)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column.py", line 2289, in get
    transformed = column._transform_feature(self)  # pylint: disable=protected-access
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column.py", line 2468, in _transform_feature
    input_tensor = inputs.get(self.key)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column.py", line 2281, in get
    raise ValueError('Feature {} is not in features dictionary.'.format(key))
ValueError: Feature item_features is not in features dictionary.

originally defined at:
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/estimator/canned/dnn.py", line 108, in dnn_logit_fn
    name='dnn')
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/estimator/canned/dnn.py", line 143, in __init__
    create_scope_now=False)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/feature_column/feature_column.py", line 323, in __init__
    self._name, _internal_input_layer, create_scope_now_=create_scope_now)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 154, in make_template
    **kwargs)
```

**Comment by ajhepburn** [comment]
Aaaand I've copied a line in wrong:

`items = data.drop_duplicates(ITEM_COL)[[ITEM_COL]].reset_index(drop=True)`
instead of
`items = data.drop_duplicates(ITEM_COL)[[ITEM_COL, ITEM_FEAT_COL]].reset_index(drop=True)`
