### ISSUE TITLE
[BUG] SAR Predict Error

### ISSUE THREAD

**Issue by gramhagen** [Microsoft/Recommenders#696]
### Description
SAR predict method does not work

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\scgraham\repos\Recommenders\reco_utils\recommender\sar\sar_singlenode_old.py", line 352, in predict
    np.arange(test_scores.shape[0]), item_ids
IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (9,)
```

### In which platform does it happen?
all

### How do we replicate the issue?
```
    model = SARSingleNode()
    train = pd.DataFrame(dict(userID=[1,2,3], itemID=[4,5,6], rating=[3.0,2.0,1.0]))
    model.fit(train)

    user_items = itertools.product(train["userID"].unique(), train["itemID"].unique())
    test = pd.DataFrame(user_items, columns=["userID", "itemID"])
    preds = model.predict(test)
```

### Expected behavior (i.e. solution)
generates predictions for each row in test

### Other Comments

**Comment by gramhagen** [comment]
fixed in #697
