### ISSUE TITLE
[BUG] Permission denied in Windows test machine

### ISSUE THREAD

**Issue by miguelgfierro** [microsoft/recommenders#993]
### Description

```

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\conda\core\link.py", line 622, in _execute_actions
    action.execute()
  File "C:\Anaconda\lib\site-packages\conda\core\path_actions.py", line 373, in execute
    force=context.force)
  File "C:\Anaconda\lib\site-packages\conda\gateways\disk\create.py", line 339, in create_link
    copy(src, dst)
  File "C:\Anaconda\lib\site-packages\conda\gateways\disk\create.py", line 280, in copy
    _do_copy(src, dst)
  File "C:\Anaconda\lib\site-packages\conda\gateways\disk\create.py", line 293, in _do_copy
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Anaconda\\envs\\nightly_reco_gpu\\vcruntime140.dll'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\conda\core\link.py", line 553, in _execute
    cls._execute_actions(pkg_idx_tracked, axngroup)
  File "C:\Anaconda\lib\site-packages\conda\core\link.py", line 638, in _execute_actions
    reverse_excs,
conda.CondaMultiError: [Errno 13] Permission denied: 'C:\\Anaconda\\envs\\nightly_reco_gpu\\vcruntime140.dll'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\conda\exceptions.py", line 1003, in __call__
    return func(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda_env\cli\main.py", line 73, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\Anaconda\lib\site-packages\conda_env\cli\main_create.py", line 101, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "C:\Anaconda\lib\site-packages\conda_env\installers\conda.py", line 31, in install
    unlink_link_transaction.execute()
  File "C:\Anaconda\lib\site-packages\conda\core\link.py", line 241, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "C:\Anaconda\lib\site-packages\conda\core\link.py", line 587, in _execute
    rollback_excs,
conda.CondaMultiError: [Errno 13] Permission denied: 'C:\\Anaconda\\envs\\nightly_reco_gpu\\vcruntime140.dll'
```

### How do we replicate the issue?

dsvm_nightly_win_gpu
-> https://dev.azure.com/best-practices/recommenders/_build/results?buildId=16737

dsvm_nightly_win_cpu -> https://dev.azure.com/best-practices/recommenders/_build/results?buildId=16691

**Comment by miguelgfierro** [comment]
updated conda to v=4.7.12 with 

`conda update -n base -c defaults conda`

**Comment by miguelgfierro** [comment]
that didn't solve the issue:
```
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
Warning: 2 possible package resolutions (only showing differing packages):
  - defaults::jupyter_console-5.2.0-py36_1, defaults::prompt_toolkit-3.0.0-py_0
  - defaults::jupyter_console-6.0.0-py36_0, defaults::prompt_toolkit-2.0.10-py_0done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'defaults::pywin32-223-py36hfa6e2cd_1'.
Rolling back transaction: ...working... done

[Errno 13] Permission denied: 'C:\\Anaconda\\envs\\nightly_reco_base\\Lib\\site-packages\\win32comext\\shell\\shell.pyd'
()
```

and 
```
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
Warning: 2 possible package resolutions (only showing differing packages):
  - defaults::jupyter_console-5.2.0-py36_1, defaults::prompt_toolkit-3.0.0-py_0
  - defaults::jupyter_console-6.0.0-py36_0, defaults::prompt_toolkit-2.0.10-py_0done
initializing UnlinkLinkTransaction with
  target_prefix: C:\Anaconda\envs\nightly_reco_gpu
  unlink_precs:
    
  link_precs:
    defaults::_tflow_select-2.1.0-gpu
    defaults::blas-1.0-mkl
    defaults::ca-certificates-2019.10.16-0
    defaults::cudatoolkit-9.0-1
    defaults::icc_rt-2019.0.0-h0cc432a_1
    defaults::intel-openmp-2019.4-245
    defaults::msys2-conda-epoch-20160418-1
    defaults::pandoc-2.2.3.2-0
    defaults::vs2015_runtime-14.16.27012-hf0eaf9b_0


defaults::seaborn-0.9.0-pyh91ea838_1
    defaults::tensorflow-1.12.0-gpu_py36ha5f9131_0
    defaults::tensorflow-gpu-1.12.0-h0d30ee6_0


Preparing transaction: ...working... done
[ClobberError: The package 'defaults::vs2015_runtime-14.16.27012-hf0eaf9b_0' cannot be installed due to a
path collision for 'vcruntime140.dll'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
Verifying transaction: ...working... done
doesn't recognize. It may have been created by another package manager.

, ClobberError: The package 'defaults::pywin32-223-py36hfa6e2cd_1' cannot be installed due to a
path collision for 'lib/site-packages/win32/_win32sysloader.pyd'.
This path already exists in the target prefix, and it won't be removed
by an uninstall action in this transaction. The path is one that conda
doesn't recognize. It may have been created by another package manager.

```

**Comment by miguelgfierro** [comment]
Some temp files could not be erased, I reboot and was able to erase completely the corrupted environment. Now I kicked off the nightly builds again, they will take several hours

**Comment by miguelgfierro** [comment]
fixed by rebooting, now we have a new error https://github.com/microsoft/recommenders/issues/997
